apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: git-server-deployment
  labels:
    app: git
spec:
  replicas: 3
  template:
    metadata:
      labels:
        app: git
    spec:
      volumes:
      - name: nfs
        persistentVolumeClaim:
          claimName: nfs-pvc
      containers:
      - name: git-server
        image: git-server
        imagePullPolicy: IfNotPresent
        ports:
          - containerPort: 80
        volumeMounts:
          - name: nfs
            mountPath: "/git-server"
