kind: Service
apiVersion: v1
metadata:
  name: git-server-service
spec:
  type: NodePort
  selector:
    app: git
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 22
      nodePort: 32222
